apiVersion: apps/v1	#与k8s集群版本有关，使用 kubectl api-versions 即可查看当前集群支持的版本
kind: StatefulSet 	#该配置的类型，我们使用的是 Deployment
metadata:	        #译名为元数据，即 Deployment 的一些基本属性和信息
  name: site-oldbackend-statefulset	#Deployment 的名称
  labels:	    #标签，可以灵活定位一个或多个资源，其中key和value均可自定义，可以定义多组，目前不需要理解
    app: site-oldbackend	#为该Deployment设置key为app，value为nginx的标签
spec:
  replicas: 1	#使用该Deployment创建两个应用程序实例
  selector:	    #标签选择器，与上面的标签共同作用，目前不需要理解
    matchLabels: #选择包含标签app:nginx的资源即为下面template的模板中包含 app:nginx的模板
      app: site-oldbackend
  template:
    metadata:	#Pod的元数据
      labels:	#Pod的标签，上面的selector即选择包含标签app:nginx的Pod
        app: site-oldbackend
    spec:	    #期望Pod实现的功能（即在pod中部署）
      containers:	#生成container，与docker中的container是同一种
      - name: old-backend	#container的名称
        image: python:3.9  #创建container，该container默认80端口可访问
        ports:
        - containerPort: 8000
          name: django-port
        command: ["/bin/sh","-c"]
        args:
          - |
            mkdir /root/.pip/
            cp pip.conf /root/.pip/pip.conf
            pip install -r requirements.txt  --default-timeout=1000
            echo "start oldbackend grpc server"
            supervisord  -c grpc.conf
            python manage.py makemigrations
            python manage.py migrate
            echo "start oldbackend rest server"
            gunicorn -c gunicorn.py core.asgi:application
        volumeMounts:
          - name: django-app
            mountPath: /app
        workingDir: /app
        envFrom:
          - configMapRef:
              name: site-config         
      volumes:
        - name: django-app
          persistentVolumeClaim:
            claimName: pvc-django-app-src-code
---
#### service
apiVersion: v1
kind: Service
metadata:
  name:  svc-site-oldbackend
  labels:
    app: svc-site-oldbackend
spec:
  selector:
    app: site-oldbackend
  ports:
    - name: internal-service-django-app
      port: 8000          # 服务访问端口
      targetPort: 8000       # 容器端口
      nodePort: 30010     # NodePort
  type: NodePort

--- 
### mount-django-app-src-code
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-django-app-src-code
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /site/site-backend-rebuild/oldbackend  # 源码目录 
    type: DirectoryOrCreate
  claimRef: # 确保其他 volume不会绑定到该 PV
    name: pvc-django-app-src-code
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-django-app-src-code
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-django-app-src-code
