# This is a basic workflow to help you get started with Actions

name: DEPLOY_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - "v*"
    # branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package_front:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}/front

    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # - name: Set working directory and run commands
      #   run: |
      #     echo "Working in the specified directory"
      #     echo ${{github.workspace}}/front
      #     cd  ${{github.workspace}}/front
      #     ls -la

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'
      
      - name: Install yarn  
        run: npm install -g yarn
      - name: install dependency
        run: yarn install
      - name: build
        run: yarn build
      # - name: SSH Server Deploy
      #   uses: kostya-ten/ssh-server-deploy@v4
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     port: "22"
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     scp_source: ./dist/
      #     scp_target: /pythons/site-new
